/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(EventsInit.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a0ce1ec7b27c649865001da375ea4d3f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pus/EventsInit.h>
// pydoc.h is automatically generated in the build directory
#include <EventsInit_pydoc.h>

void bind_EventsInit(py::module& m)
{

    using EventsInit    = gr::pus::EventsInit;


    py::class_<EventsInit, gr::block, gr::basic_block,
        std::shared_ptr<EventsInit>>(m, "EventsInit", D(EventsInit))

        .def(py::init(&EventsInit::make),
           D(EventsInit,make)
        )
        



        ;




}








