/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(EventActionService.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ff468ad6fa46ccb8c5184d8888a6a4da)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pus/EventActionService.h>
// pydoc.h is automatically generated in the build directory
#include <EventActionService_pydoc.h>

void bind_EventActionService(py::module& m)
{

    using EventActionService    = gr::pus::EventActionService;


    py::class_<EventActionService, gr::block, gr::basic_block,
        std::shared_ptr<EventActionService>>(m, "EventActionService", D(EventActionService))

        .def(py::init(&EventActionService::make),
           py::arg("filename"),
           D(EventActionService,make)
        )
        



        ;




}








