/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(FileManagementService.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6607e6b53095cc5816a62b960cf0103f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pus/FileManagementService.h>
// pydoc.h is automatically generated in the build directory
#include <FileManagementService_pydoc.h>

void bind_FileManagementService(py::module& m)
{

    using FileManagementService    = gr::pus::FileManagementService;


    py::class_<FileManagementService, gr::block, gr::basic_block,
        std::shared_ptr<FileManagementService>>(m, "FileManagementService", D(FileManagementService))

        .def(py::init(&FileManagementService::make),
           py::arg("homePath"),
           D(FileManagementService,make)
        )
        



        ;




}








