/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(HousekeepingService.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fab3bf3cc4577f9e156849322e453f8a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pus/HousekeepingService.h>
// pydoc.h is automatically generated in the build directory
#include <HousekeepingService_pydoc.h>

void bind_HousekeepingService(py::module& m)
{

    using HousekeepingService    = gr::pus::HousekeepingService;


    py::class_<HousekeepingService, gr::block, gr::basic_block,
        std::shared_ptr<HousekeepingService>>(m, "HousekeepingService", D(HousekeepingService))

        .def(py::init(&HousekeepingService::make),
           py::arg("init_file"),
           D(HousekeepingService,make)
        )
        



        ;




}








