/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(LargeMessageDetector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5a793ee9cd415d4d360024a733b82404)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pus/LargeMessageDetector.h>
// pydoc.h is automatically generated in the build directory
#include <LargeMessageDetector_pydoc.h>

void bind_LargeMessageDetector(py::module& m)
{

    using LargeMessageDetector    = gr::pus::LargeMessageDetector;


    py::class_<LargeMessageDetector, gr::block, gr::basic_block,
        std::shared_ptr<LargeMessageDetector>>(m, "LargeMessageDetector", D(LargeMessageDetector))

        .def(py::init(&LargeMessageDetector::make),
           D(LargeMessageDetector,make)
        )
        



        ;




}








