/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(MemoryManagementService.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b61e163cb2db4a601a7651468426a793)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pus/MemoryManagementService.h>
// pydoc.h is automatically generated in the build directory
#include <MemoryManagementService_pydoc.h>

void bind_MemoryManagementService(py::module& m)
{

    using MemoryManagementService    = gr::pus::MemoryManagementService;


    py::class_<MemoryManagementService, gr::block, gr::basic_block,
        std::shared_ptr<MemoryManagementService>>(m, "MemoryManagementService", D(MemoryManagementService))

        .def(py::init(&MemoryManagementService::make),
           D(MemoryManagementService,make)
        )
        



        ;




}








