/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(MessageConfig.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(40604d21a66ee51f661ac238d424d865)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pus/MessageConfig.h>
// pydoc.h is automatically generated in the build directory
#include <MessageConfig_pydoc.h>

void bind_MessageConfig(py::module& m)
{

    using MessageConfig    = gr::pus::MessageConfig;


    py::class_<MessageConfig, gr::block, gr::basic_block,
        std::shared_ptr<MessageConfig>>(m, "MessageConfig", D(MessageConfig))

        .def(py::init(&MessageConfig::make),
           D(MessageConfig,make)
        )
        



        ;




}








