/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ParametersInit.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(05ac6017005da7047177344f5d8705d9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pus/ParametersInit.h>
// pydoc.h is automatically generated in the build directory
#include <ParametersInit_pydoc.h>

void bind_ParametersInit(py::module& m)
{

    using ParametersInit    = gr::pus::ParametersInit;


    py::class_<ParametersInit, gr::block, gr::basic_block,
        std::shared_ptr<ParametersInit>>(m, "ParametersInit", D(ParametersInit))

        .def(py::init(&ParametersInit::make),
           D(ParametersInit,make)
        )
        



        ;




}








