/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ParameterStatisticsService.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f19b7dcd752042efc46f6d383523fb1b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pus/ParameterStatisticsService.h>
// pydoc.h is automatically generated in the build directory
#include <ParameterStatisticsService_pydoc.h>

void bind_ParameterStatisticsService(py::module& m)
{

    using ParameterStatisticsService    = gr::pus::ParameterStatisticsService;


    py::class_<ParameterStatisticsService, gr::block, gr::basic_block,
        std::shared_ptr<ParameterStatisticsService>>(m, "ParameterStatisticsService", D(ParameterStatisticsService))

        .def(py::init(&ParameterStatisticsService::make),
           py::arg("init_file"),
           D(ParameterStatisticsService,make)
        )
        



        ;




}








