/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(StorageAndRetrievalService.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1f42896f49c3a2020d6817dab4de5d10)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pus/StorageAndRetrievalService.h>
// pydoc.h is automatically generated in the build directory
#include <StorageAndRetrievalService_pydoc.h>

void bind_StorageAndRetrievalService(py::module& m)
{

    using StorageAndRetrievalService    = gr::pus::StorageAndRetrievalService;


    py::class_<StorageAndRetrievalService, gr::block, gr::basic_block,
        std::shared_ptr<StorageAndRetrievalService>>(m, "StorageAndRetrievalService", D(StorageAndRetrievalService))

        .def(py::init(&StorageAndRetrievalService::make),
           py::arg("init_file"),
           py::arg("vc_list"),
           py::arg("samples_per_sec"),
           D(StorageAndRetrievalService,make)
        )
        



        ;




}








