/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(TestService.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c7398ac10dc69818828306e04920684c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pus/TestService.h>
// pydoc.h is automatically generated in the build directory
#include <TestService_pydoc.h>

void bind_TestService(py::module& m)
{

    using TestService    = gr::pus::TestService;


    py::class_<TestService, gr::block, gr::basic_block,
        std::shared_ptr<TestService>>(m, "TestService", D(TestService))

        .def(py::init(&TestService::make),
           D(TestService,make)
        )
        



        ;




}








