/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(TimeBasedSchedulingService.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(33c2a18f86dcde8d7bad75ee342887dc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pus/TimeBasedSchedulingService.h>
// pydoc.h is automatically generated in the build directory
#include <TimeBasedSchedulingService_pydoc.h>

void bind_TimeBasedSchedulingService(py::module& m)
{

    using TimeBasedSchedulingService    = gr::pus::TimeBasedSchedulingService;


    py::class_<TimeBasedSchedulingService, gr::block, gr::basic_block,
        std::shared_ptr<TimeBasedSchedulingService>>(m, "TimeBasedSchedulingService", D(TimeBasedSchedulingService))

        .def(py::init(&TimeBasedSchedulingService::make),
           D(TimeBasedSchedulingService,make)
        )
        



        ;




}








